# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brumethon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Brumethon
  pod "DropDown"
  pod 'Alamofire', '~> 5.5'

  target 'BrumethonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrumethonUITests' do
    # Pods for testing
  end

end
